server:
  port: 8081

spring:
  application.name: SPRING-REDIS
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console/

  cache:
    type: redis
    redis.time-to-live: 60000
    cache-names: USER_KEY

  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    root: INFO
    com.redis.example.*: DEBUG
    org.hibernate.*: DEBUG